### ISSUE TITLE
/v feat: add spine exceptions

### ISSUE THREAD

**Issue by Nikke-db** [Nikke-db/nikke-db-vue#19]
some assets are 4.0 but cover and aim 4.1 ...
old rapi/shifty need skin "00" ..
snow white gun..
skins acc..
skins bg...

**Comment by Nikke-db** [comment]
// exception list when a character have spine 4.1 and 4.0 assets
      if (id === "c131_01" && current_l2d === "aim") spineVersionLoader = spine //pepper's skin
      if (id === "c160" && current_l2d === "fb") spineVersionLoader = spine41 // yuni
      if (id === "c161" && current_l2d === "fb") spineVersionLoader = spine41 // mihara

**Comment by Koshirei** [comment]
add in the l2d store

**Comment by Koshirei** [comment]
not added in l2d store
