### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by digisomni** [Nikke-db/nikke-db-vue#35]
Just so contributors know what to expect when pushing things to the repo. My personal preference is toward permissive licensing such as Apache, MIT, and so on for any project that isn't meant to be private.

**Comment by Koshirei** [comment]
I haven't had true contributions for the past year and a half so whatever works, not sure what I'm supposed to setup

**Comment by digisomni** [comment]
Just a license file and/or filling out the license field in the package.json.

**Comment by Koshirei** [comment]
hopefully this'll do, reopen if not. I don't really care enough to read each and every licenses to know their purposes, I just took the first funny one. this project isn't that serious and people don't give me much credits for it, doubt adding a couple words in an unseen json and .md will change a thing.
